name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npx cypress run --record --key 150b3dc3-cf58-428a-a652-467cc8df18a7
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
